### ISSUE TITLE
Solver access issue

### ISSUE THREAD

**Issue by jclachance** [maranasgroup/MinimalGenome#1]
Hi,

First of all thank you for that software. 

I am trying to run it on my machine and I have issues providing pulp with access to CPLEX. Nevertheless I can make it access Gurobi. I was wondering if, during the testing/optimization of the package, you had already tested whether CPLEX was a better solver to use for that purpose or if both solvers were basically equal?

Thank you,
JC

**Comment by jclachance** [comment]
I must have been using an older version of the code. I realized that the iterative solving uses gurobi. Closing this.

**Comment by fromseto** [comment]
@jclachance Sorry for the late reply. Somehow the github notification went to my spam inbox. CPLEX and GUROBI should give the same solution. My experience is that they are better or worse than each other in terms of the speed of solving certain MILP problems.

For the problem of calling cplex in pulp, you may try to use the interface CPLEX_PY() if CPLEX_CMD() does not work properly.

Hope this helps.

Best,
Lin
